---
- name: Verificar gestores de paquetes según el sistema operativo
  hosts: all
  gather_facts: true

  tasks:
    - name: Incluir playbook de Winget si el host es Windows
      include_tasks: Win-Ecosys.yml
      when: ansible_facts.os_family == "Windows"

    - name: Incluir playbook de Homebrew si el host es macOS
      include_tasks: OsX-Ecosys.yml
      when: ansible_facts.os_family == "Darwin"
      